services:

  _defaults:
    autowire: true

  _instanceof:
    HeimrichHannot\ContaoExporterBundle\Exporter\ExporterInterface:
      tags: ['huh_exporter.exporter']
      autowire: true
      lazy: true

# Manager

  huh.exporter.manager.exporter:
    class: HeimrichHannot\ContaoExporterBundle\Manager\ExporterManager

# Listener

  huh.exporter.listener.dc.exporter:
    class: HeimrichHannot\ContaoExporterBundle\EventListener\DataContainer\Exporter
  huh.exporter.listener.dc.module:
    class: HeimrichHannot\ContaoExporterBundle\EventListener\DataContainer\Module

# Actions

  huh.exporter.action.export:
    class: HeimrichHannot\ContaoExporterBundle\Action\ExportAction
  huh.exporter.action.backendexport:
    class: HeimrichHannot\ContaoExporterBundle\Action\BackendExportAction
  huh.exporter.action.frontendexport:
    class: HeimrichHannot\ContaoExporterBundle\Action\FrontendExportAction

# Exporter

  HeimrichHannot\ContaoExporterBundle\Exporter\Concrete\CsvExporter: ~
  HeimrichHannot\ContaoExporterBundle\Exporter\Concrete\ExcelExporter: ~
  HeimrichHannot\ContaoExporterBundle\Exporter\Concrete\XlsxExporter: ~
  HeimrichHannot\ContaoExporterBundle\Exporter\Concrete\PdfExporter: ~
  HeimrichHannot\ContaoExporterBundle\Exporter\Concrete\MediaExporter: ~