services:

  _defaults:
    autowire: true

  _instanceof:
    HeimrichHannot\ContaoExporterBundle\Exporter\ExporterInterface:
      tags: ['huh_exporter.exporter']
      autowire: true
      lazy: true

# Manager

  huh.exporter.manager.exporter:
    class: HeimrichHannot\ContaoExporterBundle\ContaoManager\ExporterManager
  huh.exporter.manager.module:
    class: HeimrichHannot\ContaoExporterBundle\ContaoManager\ModuleManager

# Listener

  huh.exporter.listener.dc.exporter:
    class: HeimrichHannot\ContaoExporterBundle\EventListener\DataContainer\Exporter
  huh.exporter.listener.dc.module:
    class: HeimrichHannot\ContaoExporterBundle\EventListener\DataContainer\Module

# Actions

  huh.exporter.action.export:
    class: HeimrichHannot\ContaoExporterBundle\Action\ExportAction
  huh.exporter.action.backendexport:
    class: HeimrichHannot\ContaoExporterBundle\Action\BackendExportAction

# Exporter

  HeimrichHannot\ContaoExporterBundle\Exporter\Concrete\CsvExporter: ~
  HeimrichHannot\ContaoExporterBundle\Exporter\Concrete\XlsExporter: ~
  HeimrichHannot\ContaoExporterBundle\Exporter\Concrete\XlsxExporter: ~
  HeimrichHannot\ContaoExporterBundle\Exporter\Concrete\PdfExporter: ~
  HeimrichHannot\ContaoExporterBundle\Exporter\Concrete\MediaExporter: ~