services:

  _defaults:
    autowire: true

  _instanceof:
    HeimrichHannot\ContaoExporterBundle\Exporter\ExporterInterface:
      tags: ['huh_exporter.exporter']
      lazy: true

# Manager

  huh.exporter.manager.exporter:
    class: HeimrichHannot\ContaoExporterBundle\Manager\ExporterManager
  HeimrichHannot\ContaoExporterBundle\Manager\ExporterManager: '@huh.exporter.manager.exporter'

# Listener

  huh.exporter.listener.dc.exporter:
    class: HeimrichHannot\ContaoExporterBundle\EventListener\DataContainer\ExporterListener
  huh.exporter.listener.dc.module:
    class: HeimrichHannot\ContaoExporterBundle\EventListener\DataContainer\ModuleListener

# Actions

  huh.exporter.action.export:
    class: HeimrichHannot\ContaoExporterBundle\Action\ExportAction
  huh.exporter.action.backendexport:
    class: HeimrichHannot\ContaoExporterBundle\Action\BackendExportAction
    public: true
  huh.exporter.action.frontendexport:
    class: HeimrichHannot\ContaoExporterBundle\Action\FrontendExportAction
    public: true

# Commands

  huh.exporter.command.migration:
    class: HeimrichHannot\ContaoExporterBundle\Command\MigrationCommand
    tags:
      - { name: 'console.command'}

# Exporter

  HeimrichHannot\ContaoExporterBundle\Exporter\Concrete\CsvExporter: ~
  HeimrichHannot\ContaoExporterBundle\Exporter\Concrete\ExcelExporter: ~
  HeimrichHannot\ContaoExporterBundle\Exporter\Concrete\XlsxExporter: ~
  HeimrichHannot\ContaoExporterBundle\Exporter\Concrete\PdfExporter: ~
  HeimrichHannot\ContaoExporterBundle\Exporter\Concrete\MediaExporter: ~